# Generated by Django 5.2.3 on 2025-06-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
