# Generated by Django 5.2.3 on 2025-06-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
