# Generated by Django 5.2.3 on 2025-06-19 19:17

import cloudinary_storage.storage
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_alter_skill_options_and_more'), ('core', '0003_alter_personalinfo_bio_alter_personalinfo_title'), ('core', '0004_alter_skill_options_remove_skill_is_featured_and_more'), ('core', '0005_alter_skill_category_alter_skill_icon'), ('core', '0006_alter_skill_category'), ('core', '0007_alter_skill_category'), ('core', '0008_remove_personalinfo_portfolio_url_and_more'), ('core', '0009_alter_personalinfo_profile_picture_and_more'), ('core', '0010_alter_personalinfo_profile_picture_and_more'), ('core', '0011_alter_personalinfo_profile_picture_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('software', 'Software'), ('tools', 'Tools'), ('other', 'Other')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text="React (FontAwesome) icon class, e.g. 'fab fa-react'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_message', models.CharField(blank=True, help_text="e.g., 'Available for freelance projects starting January 2024'", max_length=200)),
                ('is_available_for_work', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Personal Information',
                'verbose_name_plural': 'Personal Information',
            },
        ),
    ]
