# Generated by Django 5.2.3 on 2025-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='availability_message',
            field=models.CharField(blank=True, help_text="e.g., 'Available for freelance projects starting January 2024'", max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='is_available_for_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(help_text='Your professional bio/about section'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(help_text='e.g., Full Stack Developer', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database & Storage'), ('tools', 'Tools & Technologies'), ('languages', 'Programming Languages'), ('soft', 'Soft Skills'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fab fa-react)', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=3, help_text='Rate your proficiency from 1-5'),
        ),
    ]
