# Generated by Django 5.2.3 on 2025-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
