# Generated by Django 5.2.3 on 2025-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personalinfo_bio_alter_personalinfo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
