# Generated by Django 5.2.3 on 2025-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='twitter_url',
        ),
    ]
