# Generated by Django 5.2.3 on 2025-06-19 18:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personalinfo_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resume/'),
        ),
    ]
