# Generated by Django 5.2.3 on 2025-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_personalinfo_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Résumé (public URL)'),
        ),
    ]
