# Generated by Django 5.2.3 on 2025-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('project', 'Project Collaboration'), ('job', 'Job Opportunity'), ('freelance', 'Freelance Work'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for follow-up'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
