# Generated by Django 5.2.3 on 2025-06-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_contactinfo_contactmessage_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='inquiry_type',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_replied',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
