# Generated by Django 5.2.3 on 2025-06-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('puzzle', 'Puzzle'), ('arcade', 'Arcade'), ('strategy', 'Strategy'), ('adventure', 'Adventure')], default='arcade', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('has_high_scores', models.BooleanField(default=True)),
                ('max_high_scores', models.IntegerField(default=10, help_text='Maximum number of high scores to keep')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('instructions', models.TextField(blank=True, help_text='How to play instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('level_reached', models.IntegerField(default=1)),
                ('play_time', models.DurationField(blank=True, help_text='Time played in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('game', 'player_name', 'score')},
            },
        ),
    ]
