# Generated by Django 5.2.3 on 2025-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty_levels',
            field=models.JSONField(blank=True, help_text='JSON array of difficulty settings', null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='session_data',
            field=models.JSONField(blank=True, help_text='Additional game session data', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='Game description and rules'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('puzzle', 'Puzzle'), ('arcade', 'Arcade'), ('strategy', 'Strategy'), ('adventure', 'Adventure'), ('casual', 'Casual')], default='arcade', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_high_scores',
            field=models.BooleanField(default=True, help_text='Does this game track high scores?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the game available to play?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Game thumbnail image', null=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='play_time',
            field=models.DurationField(blank=True, help_text='How long the game was played', null=True),
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
